# -*- coding: utf-8 -*-
"""GOOGLE PLAYSTORE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SwYQBr2lRHAVes37of86wOdSMGEzII8y
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as mn

google = pd.read_csv('Google-Playstore[1].csv')

google

google.shape

google.isnull()

google.describe()

google.isnull().sum()

google.info()

google.columns

google.isnull().sum().sort_values(ascending = False)

!pip install missingno

mn.heatmap(google)

mn.bar(google)

mn.matrix(google)

missing_percentage = google.isnull().sum().sort_values(ascending = False)/len(google)
missing_percentage = missing_percentage[missing_percentage!=0]
import matplotlib
plt.rcParams['figure.figsize']=(20,10)
missing_percentage.plot(kind = 'barh')

missing_percentage = google.isnull().sum().sort_values(ascending = False)/len(google)
missing_percentage = missing_percentage[missing_percentage!=0]
import matplotlib
sns.set_style('darkgrid')
plt.rcParams['figure.figsize']=(20,10)
missing_percentage.plot(kind = 'barh')

missing_percentage = google.isnull().sum().sort_values(ascending = False)/len(google)
missing_percentage = missing_percentage[missing_percentage!=0]
import matplotlib
sns.set_style('whitegrid')
plt.rcParams['figure.figsize']=(20,10)
missing_percentage.plot(kind = 'barh')

google.dropna(subset=['Category','Maximum Install','Free','Price','Size','App Id','Developer Id','Scraped Time','Last Updated','Content Rating','Ad Supported','In App Purchases','Editors Choice','Developer Email','Currency','Minimum Installs','Install'],inplace = True)